tongxiangmj:
  ports:
  - 5105:5105/tcp
  - 18005:8003/tcp
  - 28005:7788/tcp
  environment:
    NODETYPE: MJGame/tongxiangmj
    nodeid: '37'
    RUNENV: develop
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: dockerhub.ucop.io/mobile/mgserver:develop-2017062702
  volumes:
  - /data/log/mobilegame:/app/log
  stdin_open: true
