wuhumj:
  ports:
  - 5111:5111/tcp
  - 18011:8003/tcp
  - 28011:7788/tcp
  environment:
    NODETYPE: MJGame/wuhumj
    nodeid: '19'
    RUNENV: develop
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: dockerhub.ucop.io/mobile/mgserver:develop-2017062303
  volumes:
  - /data/log/mobilegame:/app/log
  stdin_open: true
