wuzhenmj:
  ports:
  - 5109:5109/tcp
  - 18009:8003/tcp
  - 28009:7788/tcp
  environment:
    NODETYPE: MJGame/wuzhenmj
    nodeid: '36'
    RUNENV: develop
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: dockerhub.ucop.io/mobile/mgserver:develop-046f7a
  volumes:
  - /data/log/mobilegame:/app/log
  stdin_open: true