xinghuamj:
  ports:
  - 5113:5113/tcp
  - 18013:8003/tcp
  - 28013:7788/tcp
  environment:
    NODETYPE: MJGame/xinghuamj
    nodeid: '47'
    RUNENV: develop
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: dockerhub.ucop.io/mobile/mgserver:develop-2017062704
  volumes:
  - /data/log/mobilegame:/app/log
  stdin_open: true
